services:
  wg-easy:
    environment:
      - WG_HOST=${IP} #change ${IP} to this VM IP
      - WG_PORT=1194
      - WG_DEFAULT_DNS=192.168.200.1 #change it to proper value
      - WG_ALLOWED_IPS=192.168.200.0/22
      - WG_DEFAULT_ADDRESS=192.168.198.x
      - PASSWORD_HASH=$$2a$$12$$9jy12/wwr0VK5NczmsZcju6wvct6K84otbByLqyjHlvK9ITFgXKXq #password: foobar, change it by executing "docker run -it ghcr.io/wg-easy/wg-easy wgpw 'YOUR_PASSWORD'" and paste here without ' or " and double $ (add an additional $ before each existing $ symbol)
      - UI_ENABLE_SORT_CLIENTS=true
      - WG_ENABLE_ONE_TIME_LINKS=true
      - UI_CHART_TYPE=1
      - UI_TRAFFIC_STATS=true
    image: ghcr.io/wg-easy/wg-easy
    container_name: vpn
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
