services:
  app0:
    image: strm/helloworld-http:latest
    container_name: "app0"
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app0.entrypoints=web-secure"
      - "traefik.http.routers.app0.rule=Host(`app0.homelab.local`)"
      - "traefik.http.routers.app0.tls=true"
      - "traefik.http.routers.app0.tls.certresolver=tlschallenge"
      - "traefik.http.routers.app0.middlewares=secHeaders@file"
      - "traefik.http.services.app0.loadbalancer.server.url=http://${IP}:8081"
    restart: unless-stopped
