services:
  fileshare:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - 81:80
    restart: unless-stopped
    volumes:
      - './files:/srv:rw'
      - './filebrowser.db:/database.db:rw'
      - './.filebrowser.json:/.filebrowser.json:rw'
