services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine3.18
    container_name: gitlab-runner
    restart: unless-stopped
    volumes:
      - './gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    enviroment:
      TZ: "Europe/Zurich"
