services:
  ca:
    image: smallstep/step-ca:0.27.4
    container_name: "ca"
    ports:
      - "9000:9000"
    volumes:
      - "./step:/home/step"
    environment:
      DOCKER_STEPCA_INIT_NAME: "CA"
      DOCKER_STEPCA_INIT_DNS_NAMES: "ca.homelab.lan ca.homelab.internal"
      DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: "true"
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.ca.entrypoints=web-secure"
      #- "traefik.http.routers.ca.rule=Host(`ca.homelab.lan`)"
      #- "traefik.http.routers.ca.tls=true"
      #- "traefik.http.routers.ca.tls.certresolver=tlschallenge"
      #- "traefik.http.routers.ca.middlewares=secHeaders@file"
      #- "traefik.http.services.app0.loadBalancer.server.url=http://app0.homelab.internal:9000"
    restart: unless-stopped
