services:
  ca:
    image: smallstep/step-ca:0.27.4
    container_name: "ca"
    ports:
      - "9000:9000"
    volumes:
      - "./step:/home/step"
    environment:
      DOCKER_STEPCA_INIT_NAME: "CA"
      DOCKER_STEPCA_INIT_DNS_NAMES: "ca.homelab.lan ca.homelab.internal"
      DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: "true"
    restart: unless-stopped
