#https://github.com/pi-hole/docker-pi-hole/blob/master/examples/docker-compose-caddy-proxy.yml
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - '4053:53/tcp' #Change 4053 -> 53
      - '4053:53/udp' #Change 4053 -> 53
      - "4067:67/udp" #Only required if you are using Pi-hole as your DHCP server, change 4067 -> 67
      - '80:80/tcp'
    environment:
      TZ: "Europe/Zurich" #Change it to yout TZ
    volumes:
      - './pihole:/etc/pihole'
      - './dnsmasq.d:/etc/dnsmasq.d'
      - './log/pihole.log:/var/log/pihole/pihole.log'
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - 'router router.homelab.lan:192.168.199.1'
      - 'firewall firewall.homelab.lan:192.168.199.2'
      - 'firewall firewall.homelab.lan:192.168.200.1'
      - 'proxmox proxmox.homelab.lan:192.168.200.2'
      - 'switch switch.homelab.lan:192.168.200.3'
      - 'ap0 ap0.homelab.lan:192.168.200.4'
      - 'ap1 ap1.homelab.lan:192.168.200.5'
      - 'ap2 ap2.homelab.lan:192.168.200.6'
      - 'traefik traefik.homelab.lan:192.168.200.7'
      - 'ca ca.homelab.lan:192.168.200.8'
      - 'pihole pihole.homelab.lan:192.168.200.9'
      - 'vpn vpn.homelab.lan:192.168.200.10'
      - 'gitlab gitlab.homelab.lan:192.168.200.11'
      - 'runner1 runner1.homelab.lan:192.168.200.12'
      - 'runner2 runner2.homelab.lan:192.168.200.13'
      - 'runner3 runner3.homelab.lan:192.168.200.14'
      - 'runner4 runner4.homelab.lan:192.168.200.15'
      - 'runner5 runner5.homelab.lan:192.168.200.16'
      - 'runner6 runner6.homelab.lan:192.168.200.17'
      - 'runner7 runner7.homelab.lan:192.168.200.18'
      - 'runner8 runner8.homelab.lan:192.168.200.19'
      - 'files files.homelab.lan:192.168.200.20'
      - 'wiki wiki.homelab.lan:192.168.200.21'
      - 'mattermost mattermost.homelab.lan:192.168.200.22'
      - 'bugs bugs.homelab.lan:192.168.200.23'
      - 'deployment deployment.homelab.lan:192.168.200.24'
      - 'grafana grafana.homelab.lan:192.168.200.25'
      #Add others if required
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app0.entrypoints=web-secure"
      - "traefik.http.routers.app0.rule=Host(`pihole.homelab.lan`)"
      - "traefik.http.routers.app0.tls=true"
      - "traefik.http.routers.app0.tls.certresolver=tlschallenge"
      - "traefik.http.routers.app0.middlewares=secHeaders@file"
      - "traefik.http.services.app0.loadbalancer.server.url=http://${IP}:80"
