#https://github.com/pi-hole/docker-pi-hole/blob/master/examples/docker-compose-caddy-proxy.yml
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - '4053:53/tcp' #Change 4053 -> 53
      - '4053:53/udp' #Change 4053 -> 53
      - "4067:67/udp" #Only required if you are using Pi-hole as your DHCP server, change 4067 -> 67
      - '8080:80/tcp'
    environment:
      TZ: "Europe/Zurich" #Change it to yout TZ
    volumes:
      - './pihole:/etc/pihole'
      - './dnsmasq.d:/etc/dnsmasq.d'
      - './log/pihole.log:/var/log/pihole/pihole.log'
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - 'router router.homelab.internal:192.168.199.1'
      - 'firewall firewall.homelab.internal:192.168.199.2'
      - 'firewall firewall.homelab.internal:192.168.200.1'
      - 'proxmox proxmox.homelab.internal:192.168.200.2'
      - 'switch switch.homelab.internal:192.168.200.3'
      - 'ap0 ap0.homelab.internal:192.168.200.4'
      - 'ap1 ap1.homelab.internal:192.168.200.5'
      - 'ap2 ap2.homelab.internal:192.168.200.6'
      - 'traefik traefik.homelab.internal:192.168.200.7'
      - 'ca ca.homelab.internal:192.168.200.7'
      - 'pihole pihole.homelab.internal:192.168.200.7'
      - 'vpn vpn.homelab.internal:192.168.200.8'
      - 'gitlab gitlab.homelab.internal:192.168.200.8'
      - 'runner1 runner1.homelab.internal:192.168.200.9'
      - 'runner2 runner2.homelab.internal:192.168.200.10'
      - 'runner3 runner3.homelab.internal:192.168.200.11'
      - 'runner4 runner4.homelab.internal:192.168.200.12'
      - 'runner5 runner5.homelab.internal:192.168.200.13'
      - 'runner6 runner6.homelab.internal:192.168.200.14'
      - 'runner7 runner7.homelab.internal:192.168.200.15'
      - 'runner8 runner8.homelab.internal:192.168.200.16'
      - 'files files.homelab.internal:192.168.200.8'
      - 'wiki wiki.homelab.internal:192.168.200.8'
      - 'mattermost mattermost.homelab.internal:192.168.200.8'
      - 'bugs bugs.homelab.internal:192.168.200.8'
      - 'deployment deployment.homelab.internal:192.168.200.17'
      - 'grafana grafana.homelab.internal:192.168.200.8'
      - 'metrics metrics.homelab.internal:192.168.200.8'
      - 'router.homelab.lan:192.168.199.7'
      - 'firewall.homelab.lan:192.168.200.1'
      - 'proxmox.homelab.lan:192.168.200.7'
      - 'switch.homelab.lan:192.168.200.7'
      - 'ap0.homelab.lan:192.168.200.7'
      - 'ap1.homelab.lan:192.168.200.7'
      - 'ap2.homelab.lan:192.168.200.7'
      - 'traefik.homelab.lan:192.168.200.7'
      - 'ca.homelab.lan:192.168.200.7'
      - 'pihole.homelab.lan:192.168.200.7'
      - 'vpn.homelab.lan:192.168.200.7'
      - 'gitlab.homelab.lan:192.168.200.7'
      - 'files.homelab.lan:192.168.200.7'
      - 'wiki.homelab.lan:192.168.200.7'
      - 'mattermost.homelab.lan:192.168.200.7'
      - 'bugs.homelab.lan:192.168.200.7'
      - 'grafana.homelab.lan:192.168.200.7'
      - 'metrics.homelab.lan:192.168.200.7'
      #Add others if required
    restart: unless-stopped
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.pihole.entrypoints=web-secure"
      #- "traefik.http.routers.pihole.rule=Host(`pihole.homelab.lan`)"
      #- "traefik.http.routers.pihole.tls=true"
      #- "traefik.http.routers.pihole.tls.certresolver=tlschallenge"
      #- "traefik.http.routers.pihole.middlewares=secHeaders@file"
      #- "traefik.http.services.pihole.loadbalancer.server.url=http://pihole.homelab.internal:8080"
      #- "traefik.http.middlewares.test-redirectregex.redirectregex.regex=^https://pihole.homelab.lan/{0,1}$"
      #- "traefik.http.middlewares.test-redirectregex.redirectregex.replacement=https://pihole.homelab.lan/admin"
