services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: "keycloak"
    ports:
      - "8090:8080"
    restart: unless-stopped
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin # Change it!
    command: "start-dev --hostname=https://keycloak.homelab.lan"
