#https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml
services:
  # VictoriaMetrics instance, a single process responsible for
  # storing metrics and serve read requests.
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.103.0
    ports:
      - 8088:8428
    volumes:
      - ./vmdata:/storage
      - ./config:/config:ro
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "-promscrape.config=/config/scrape.yaml"
    networks:
      - vm_net
    restart: unless-stopped

  # Grafana instance configured with VictoriaMetrics as datasource
  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.2
    depends_on:
      - "victoriametrics"
    ports:
      - 8087:3000
    volumes:
      - ./grafanadata:/var/lib/grafana
      - ./config/single.yml:/etc/grafana/provisioning/datasources/single.yml
      - ./config/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
    networks:
      - vm_net
    restart: unless-stopped

networks:
  vm_net:
