http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
    autodetectContenttype:
      contentType: {}
  tls:
    certificates:
      - certFile: /certs/traefik.homelab.lan.crt
        keyFile: /certs/traefik.homelab.lan.key
