providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
api:
  dashboard: true
entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: ':443'
certificatesResolvers:
  tlschallenge:
    acme:
      caServer: https://ca.homelab.lan:9000 #change it to your CA server or comment out
      email: work.opiela@gmail.com #change it to your email
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
