services:
  gitlab:
    image: gitlab/gitlab-ce:17.2.8-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.homelab.lan'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.homelab.lan'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '8082:80'
      #- '8443:443'
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
