services:
  mattermost:
    image: mattermost/platform:9.3.0
    container_name: "mattermost"
    ports:
      - "8085:8065"
    restart: unless-stopped
    extra_hosts:
      - "dockerhost:127.0.0.1"
